spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http:///localhost:8761/eureka/
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

